pipeline {
    agent any

    environment {
        IMAGE_NAME = 'gupthamadula/python-app'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/guptha-maddula/devops-tasks.git' // change this to your actual repo
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 5000:5000 --name hello-python $IMAGE_NAME'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up container if needed...'
            sh 'docker rm -f hello-python || true'
        }
    }
}
